title: Jason Chadwick
tagline: Jason Chadwick is a quantum computing PhD student at UChicago.
description: Jason Chadwick is a quantum computing PhD student at UChicago. He studies quantum control and high-radix computation with qudits.
logo: /assets/img/portrait-circle-small.png
google_analytics:
theme: jekyll-theme-minimal
author: Jason Chadwick

mylinks:
  - name: CV
    link: /assets/files/JasonChadwickCV.pdf
  - name: Github
    link: https://github.com/jasonchadwick
  - name: Google Scholar
    link: https://scholar.google.com/citations?user=kE5iFs0AAAAJ&hl=en&inst=5778974199078678248
  - name: LinkedIn
    link: https://www.linkedin.com/in/jasonchadwick/
  - name: ORCiD
    link: https://orcid.org/0000-0002-7932-1418

sections:
  - name: Research
    items:
      - title: "Qompress: Efficient Compilation for Ququarts Exploiting Partial and Mixed Radix Operations for Communication Reduction"
        short: We consider selectively compressing pairs of qubits into single four-state ququarts. We generate control pulses that operate on this mixed-radix space and develop a compiler to transform any quantum circuit into this framework.
        img: /assets/img/projects/qompress/mixed-radix.png
        authors: 
          - name: "Andrew Litteken,"
            link: http://andrewlitteken.com/
          - name: "Lennart Maximilian Seifert,"
            link: https://scholar.google.com/citations?user=k6RYl7kAAAAJ&hl=en&inst=5778974199078678248
          - name: "Jason Chadwick,"
          - name: "Natalia Nottingham,"
            link: 
          - name: "Jonathan M. Baker,"
            link: https://www.jonathanmarkbaker.com/
          - name: "Frederic T. Chong"
            link: https://people.cs.uchicago.edu/~ftchong/
        publisher: (to appear) ASPLOS 2023
        items:
          - name: project
            link: /projects/qompress

      - title: "Time-Efficient Qudit Gates through Incremental Pulse Re-seeding"
        short: "We present a method to iteratively obtain short-duration quantum control pulses when it is not possible to directly modify the objective function. We use this to find gate durations for high-radix logic gates that scale better than expected."
        img: /assets/img/projects/ipr/ipr.png
        authors: 
          - name: "Lennart Maximilian Seifert*,"
            link: https://scholar.google.com/citations?user=k6RYl7kAAAAJ&hl=en&inst=5778974199078678248
          - name: "Jason Chadwick*,"
          - name: "Andrew Litteken,"
            link: http://andrewlitteken.com/
          - name: "Frederic T. Chong,"
            link: https://people.cs.uchicago.edu/~ftchong/
          - name: "Jonathan M. Baker"
            link: https://www.jonathanmarkbaker.com/
        publisher: QCE 2022
        items:
          - name: pdf
            link: /assets/papers/QCE_2022_Pulse_Optimization.pdf
          - name: project
            link: /projects/ipr
          - name: IEEE Xplore
            link: "https://doi.org/10.1109/QCE53715.2022.00051"

      - title: Prediction of electron density and pressure profile shapes on NSTX-U using neural networks
        short: We develop a neural network to accurately predict cross-sectional shapes of plasma density and pressure on the NSTX-U fusion reactor. The network runs orders of magnitude faster than existing physics-based code.
        img: /assets/img/projects/tenenet.png
        authors: 
          - name: "Mark D. Boyer"
            link: https://scholar.google.com/citations?user=73UIWLEAAAAJ&inst=5778974199078678248
          - name: "Jason Chadwick"
        publisher: Nuclear Fusion 61 046024
        items:
          - name: pdf
            link: /assets/papers/TeNeNeT.pdf
          - name: project
            link: /projects/tenenet
          - name: IOPscience
            link: https://iopscience.iop.org/article/10.1088/1741-4326/abe08b
          - name: poster
            link: /assets/files/fusion-poster.pdf
          - name: slides
            link: /assets/files/fusion-slides.pdf
  - name: Projects
    description: Personal projects
    items:
      - title: Chronodrifter
        short: A 2D platformer game where the player can slow and reverse the flow of time and must solve increasingly complex puzzles. A live web version is hosted at placeholder-studios-dev.github.io/chronodrifter. Made with Unity.
        img: /assets/img/projects/chronodrifter.png
        items:
          - name: live web game
            link: https://jasonchadwick.github.io/chronodrifter
          - name: project
            link: /projects/chronodrifter
          - name: code
            link: https://github.com/jasonchadwick/chronodrifter
      - title: Quops
        img: /assets/img/projects/quops.png
        short: A board game consisting of hexagonal tiles, with each tile corresponding to a qubit. Players take turns applying quantum operations to the board to try to steer the collective board state to their target state. Graphical edition coming soon!
        items:
          - name: project
            link: /projects/quops
          - name: code
            link: https://github.com/jasonchadwick/quops-game
      - title: Cosmic string loops
        img: /assets/img/projects/strings.png
        short: "In the summer of 2019, I worked with Ken Olum at the Tufts Institute of Cosmology to study the properties of smooth cosmic string loops. I began the summer running computational simulations of cosmic strings and later transitioned to working on a mathematical proof that smooth cosmic string loops will always decay."
        items:
          - name: project
            link: /projects/cosmic-strings
  - name: Miscellaneous
    items:
      - title: "Explainer: Quantum optimal control for qudits"
        img: /assets/img/projects/x-transition.png
        short: A brief background explanation for my work with qudit quantum control.
        items:
          - name: page
            link: /projects/quantum-control
      - title: Last Minute
        img: /assets/img/projects/last-minute.png
        short: In my junior year of undergrad, some friends and I created a makeshift band to fill an open spot in CMU's annual Spring Carnival. Because we formed the band two weeks before the show date, we chose the fitting name "Last Minute". I'm all the way on stage left playing rhythm guitar!
        items:
          - name: concert video (YouTube)
            link: https://www.youtube.com/watch?v=Kg0dvcK3-HM