title: Jason D. Chadwick
tagline: Quantum computing PhD student at UChicago
description: First-year computer science Ph.D. student at the University of Chicago studying quantum computer systems with Fred Chong
logo: /assets/img/portrait.JPG
homepic: /assets/img/portrait_circle_1024.png
google_analytics:
theme: jekyll-theme-minimal
author: Jason D. Chadwick

url: https://www.jason-chadwick.com
plugins:
  - jekyll-sitemap

mylinks:
  - name: CV
    link: /assets/files/JasonChadwickCV.pdf
  - name: Github
    link: https://github.com/jasonchadwick
  - name: Google Scholar
    link: https://scholar.google.com/citations?user=kE5iFs0AAAAJ&hl=en&inst=5778974199078678248
  - name: LinkedIn
    link: https://www.linkedin.com/in/jasonchadwick/
  - name: ORCiD
    link: https://orcid.org/0000-0002-7932-1418

sections:
  - name: Research
    items:
      - title: "Efficient control pulses for continuous quantum gate families through coordinated re-optimization"
        imglink: /projects/reoptimization/
        short: We present a method that allows quantum hardware to execute arbitrary operations at the pulse level by interpolating between a small number of known reference pulses. We demonstrate the procedure on the continuous space of all two-qubit operations.
        img: /assets/img/projects/reoptimization/hero.png
        authors:
          - name: "Jason D. Chadwick"
          - name: "Frederic T. Chong"
            link: https://people.cs.uchicago.edu/~ftchong/
        publisher: QCE 2023
        award: QTEM Best Paper - 3rd place
        items:
          - name: project
            link: /projects/reoptimization
          - name: .pdf
            link: /assets/papers/chadwick_efficient_2023.pdf
          - name: arXiv
            link: https://arxiv.org/abs/2302.01553
          - name: poster
            link: /assets/files/reoptimization-poster.pdf
          - name: code
            link: https://github.com/jasonchadwick/pulse-interpolation
      - title: "Dancing the Quantum Waltz: Compiling Three-Qubit Gates on Four Level Architectures"
        imglink: /projects/waltz/
        short: We extend our previous work on qubit-to-ququart compression to specifically optimize three-qubit gates such as the Toffoli gate. We also find significant advantages in using Z-type multi-bit operations instead of X-type operations.
        img: /assets/img/projects/waltz/hero.png
        authors:
            - name: "Andrew Litteken"
              link: http://andrewlitteken.com/
            - name: "Lennart Maximilian Seifert"
              link: https://scholar.google.com/citations?user=k6RYl7kAAAAJ&hl=en&inst=5778974199078678248
            - name: "Jason D. Chadwick"
            - name: "Natalia Nottingham"
              link: https://cs.uchicago.edu/people/natalia-nottingham/
            - name: "Tanay Roy"
              link: https://sites.google.com/site/tanayroysite/
            - name: Ziqian Li
              link: https://scholar.google.com/citations?user=wplWf_UAAAAJ&hl=en&inst=5778974199078678248
            - name: David Schuster
              link: https://schusterlab.stanford.edu/
            - name: "Jonathan M. Baker"
              link: https://www.jonathanmarkbaker.com/
            - name: "Frederic T. Chong"
              link: https://people.cs.uchicago.edu/~ftchong/
        publisher: ISCA 2023
        items:
          - name: project
            link: /projects/waltz
          - name: .pdf
            link: /assets/papers/litteken_dancing_2023.pdf
          - name: ACM Digital Library
            link: https://doi.org/10.1145/3579371.3589106
          - name: arXiv
            link: https://arxiv.org/abs/2303.14069
      - title: "Qompress: Efficient Compilation for Ququarts Exploiting Partial and Mixed Radix Operations for Communication Reduction"
        imglink: /projects/qompress/
        short: We consider selectively compressing pairs of qubits into single four-state ququarts. We generate efficient "partial" operations between ququarts and qubits, which motivates a compiler that can transform any quantum circuit into this framework.
        img: /assets/img/projects/qompress/mixed-radix.png
        authors: 
          - name: "Andrew Litteken"
            link: http://andrewlitteken.com/
          - name: "Lennart Maximilian Seifert"
            link: https://scholar.google.com/citations?user=k6RYl7kAAAAJ&hl=en&inst=5778974199078678248
          - name: "Jason D. Chadwick"
          - name: "Natalia Nottingham"
            link: https://cs.uchicago.edu/people/natalia-nottingham/
          - name: "Jonathan M. Baker"
            link: https://www.jonathanmarkbaker.com/
          - name: "Frederic T. Chong"
            link: https://people.cs.uchicago.edu/~ftchong/
        publisher: ASPLOS 2023
        items:
          - name: project
            link: /projects/qompress
          - name: .pdf
            link: /assets/papers/litteken_qompress_2023.pdf
          - name: ACM Digital Library
            link: https://doi.org/10.1145/3575693.3575726
          - name: arXiv
            link: https://arxiv.org/abs/2303.00658

      - title: "Time-Efficient Qudit Gates through Incremental Pulse Re-seeding"
        imglink: /projects/ipr/
        short: "We present a method to iteratively obtain short-duration quantum control pulses when it is not possible to directly modify the objective function. We use this to find gate durations for high-radix logic gates that scale better than expected."
        extra: "* indicates equal contribution"
        img: /assets/img/projects/ipr/hero.png
        authors: 
          - name: "Lennart Maximilian Seifert*"
            link: https://scholar.google.com/citations?user=k6RYl7kAAAAJ&hl=en&inst=5778974199078678248
          - name: "Jason D. Chadwick*"
          - name: "Andrew Litteken"
            link: http://andrewlitteken.com/
          - name: "Frederic T. Chong"
            link: https://people.cs.uchicago.edu/~ftchong/
          - name: "Jonathan M. Baker"
            link: https://www.jonathanmarkbaker.com/
        publisher: QCE 2022
        items:
          - name: project
            link: /projects/ipr
          - name: .pdf
            link: /assets/papers/seifert_timeefficient_2022.pdf
          - name: IEEE Xplore
            link: https://doi.org/10.1109/QCE53715.2022.00051
          - name: arXiv
            link: https://arxiv.org/abs/2206.14975
          - name: poster
            link: /assets/files/QIP-2022.pdf

      - title: Prediction of electron density and pressure profile shapes on NSTX-U using neural networks
        imglink: /projects/tenenet/
        short: We develop a neural network to accurately predict cross-sectional shapes of plasma density and pressure on the NSTX-U fusion reactor. The network runs orders of magnitude faster than existing physics-based code.
        img: /assets/img/projects/tenenet/hero.png
        authors: 
          - name: "Mark D. Boyer"
            link: https://www.linkedin.com/in/mdboyer/
          - name: "Jason D. Chadwick"
        publisher: Nuclear Fusion 61 046024
        items:
          - name: project
            link: /projects/tenenet
          - name: .pdf
            link: /assets/papers/boyer_prediction_2021.pdf
          - name: IOPscience
            link: https://iopscience.iop.org/article/10.1088/1741-4326/abe08b
          - name: poster
            link: /assets/files/fusion-poster.pdf
          - name: slides
            link: /assets/files/fusion-slides.pdf

  - name: Projects
    description: Personal projects
    items:
      # - title: stim_lattice_surgery
      #   imglink: https://github.com/jasonchadwick/stim_lattice_surgery
      #   short: (WORK IN PROGRESS - NOT RELEASED YET) Flexible circuit-level simulation of arbitrary Litinski-style lattice surgery circuits using Stim.
      #   img: /assets/img/projects/stim_lattice_surgery.png
      #   items:
      #     - name: code
      #       link: https://github.com/jasonchadwick/stim_lattice_surgery
      - title: qc_utils
        imglink: https://github.com/jasonchadwick/qc_utils
        short: Collection of useful utility functions that I have accumulated while working on various quantum computing projects. Includes flexible state/process tomography experiments, Hamiltonian builders, many quantum logic gates, and more miscellaneous reuseable code.
        img: /assets/img/projects/qc_utils.png
        items:
          - name: code
            link: https://github.com/jasonchadwick/qc_utils
      - title: Chronodrifter
        imglink: /projects/chronodrifter/
        short: A 2D platformer game where the player can slow and reverse the flow of time to solve increasingly complex puzzles. Inspired by the game Portal and the movie Tenet. A live web version is hosted on this site. Made with Unity and C#.
        img: /assets/img/projects/chronodrifter/hero.png
        items:
          - name: project
            link: /projects/chronodrifter
          - name: live web game
            link: https://www.jason-chadwick.com/chronodrifter
          - name: code
            link: https://github.com/jasonchadwick/chronodrifter

      - title: Quops
        imglink: /projects/quops/
        img: /assets/img/projects/quops/quops.png
        short: A board game consisting of hexagonal tiles, with each tile corresponding to a qubit. Players take turns applying quantum operations to the board to try to steer the collective board state to their target state. Graphical edition coming soon!
        items:
          - name: project
            link: /projects/quops
          - name: code
            link: https://github.com/jasonchadwick/quops-game
      - title: Cosmic string loops
        imglink: /projects/cosmic-strings
        img: /assets/img/projects/strings.png
        short: "In the summer of 2019, I worked with Ken Olum at the Tufts Institute of Cosmology to study the properties of smooth cosmic string loops. I began the summer running computational simulations of cosmic strings and later transitioned to working on a mathematical proof that smooth cosmic string loops will always decay."
        items:
          - name: project
            link: /projects/cosmic-strings

  - name: Miscellaneous
    items:
      - title: "Failed Research"
        imglink: /projects/failed_research/
        img: /assets/img/projects/failed_projects.png
        short: A collection of research ideas I have tried and have not had success with - because science should encourage publication of negative results more!
        items:
          - name: page
            link: /projects/failed_research/ 
      # - title: "Explainer: Quantum optimal control for qudits"
      #   imglink: /projects/control_explainer/
      #   img: /assets/img/projects/x-transition.png
      #   short: A brief background explanation for my work with qudit quantum control.
      #   items:
      #     - name: page
      #       link: /projects/quantum-control

      - title: Last Minute
        imglink: /projects/last_minute/
        img: /assets/img/projects/last-minute.png
        short: In my junior year of undergrad, some friends and I created a makeshift band to fill an open spot in CMU's annual Spring Carnival. Because we formed the band two weeks before the show date, we chose the fitting name "Last Minute". I'm all the way on stage left playing rhythm guitar! Check out 42:20 for some improvised solos at the end.
        items:
          - name: concert video (YouTube)
            link: https://www.youtube.com/watch?v=Kg0dvcK3-HM
        imglink: https://www.youtube.com/watch?v=Kg0dvcK3-HM