#!/bin/sh

set -e

bundle exec jekyll build
if bundle exec ruby -e "exit Gem.bin_path('html-proofer', 'htmlproofer') ? 0 : 1" >/dev/null 2>&1; then
	bundle exec htmlproofer ./_site --check-html --url-ignore "/iopscience.iop.org/,/linkedin.com/"
else
	echo "Skipping htmlproofer: html-proofer gem executable is not installed."
fi
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-minimal.gemspec
